services:
  satisfactory-server:
    image: 'satisfactory-arm64'
    container_name: 'satisfactory-server'
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
      - '8888:8888/tcp'
    restart: 'unless-stopped'
    # change if you don't want satisfactory hogging compute
    ulimits:
      nice:
        soft: -20
        hard: -20
    environment:
      ALWAYS_UPDATE_ON_START: ${ALWAYS_UPDATE_ON_START:-true}
      EXPERIMENTAL_BRANCH: ${EXPERIMENTAL_BRANCH:-false}
      PUID: ${PUID:-1001}
      PGID: ${PGID:-1001}
      CPU_CORE_COUNT: ${CPU_CORE_COUNT:-4}
      SERVER_NICENESS: ${SERVER_NICENESS:-0}
      EXTRA_PARAMS: >
        -log
        -unattended
        -ini:Engine:[HTTPServer.Listeners]:DefaultBindAddress=any
    volumes:
      - './satisfactory-data:/satisfactory'
      - './config:/home/steam/.config/Epic'
      - './fex-data:/home/steam/.fex-emu'
    stdin_open: true
    tty: true
    entrypoint: /home/steam/init-server.sh